
-- Insert the locations from the image into the locations table
INSERT INTO public.locations (name, abbreviation, status, ownership_type) VALUES
  ('Pelham', 'AL_PELHAM', 'active', 'franchise'),
  ('Tuscaloosa', 'AL_TUSCALOOSA', 'active', 'franchise'),
  ('Bentonville', 'AR_BENTONVILLE', 'active', 'franchise'),
  ('Conway', 'AR_CONWAY', 'active', 'franchise'),
  ('Fayetteville', 'AR_FAYETTEVILLE', 'active', 'franchise'),
  ('Fort Smith', 'AR_FORT_SMITH', 'active', 'franchise'),
  ('Hot Springs', 'AR_HOT_SPRING', 'active', 'franchise'),
  ('Jonesboro', 'AR_JONESBORO', 'active', 'franchise'),
  ('Little Rock', 'AR_LITTLE_ROCK', 'active', 'franchise'),
  ('Paragould', 'AR_PARAGOULD', 'active', 'franchise'),
  ('Rogers', 'AR_ROGERS', 'active', 'franchise'),
  ('Siloam Springs', 'AR_SILOAM_SPRINGS', 'active', 'franchise'),
  ('Springdale', 'AR_SPRINGDALE', 'active', 'franchise'),
  ('Peoria', 'AZ_PEORIA', 'active', 'franchise'),
  ('West Phoenix', 'AZ_WEST_PHOENIX', 'active', 'franchise'),
  ('Tracy', 'CA_TRACY', 'active', 'franchise'),
  ('Boulder', 'CO_BOULDER', 'active', 'franchise'),
  ('Boulder Campus', 'CO_BOULDER_CAMPUS', 'active', 'franchise'),
  ('Buchtel', 'CO_BUCHTEL', 'active', 'franchise'),
  ('Castle Rock', 'CO_CASTLE_ROCK', 'active', 'franchise'),
  ('Downtown Denver', 'CO_DOWNTOWN_DENVER', 'active', 'franchise'),
  ('Greenwood Village', 'CO_GREENWOOD_VILLAGE', 'active', 'franchise'),
  ('Highlands Ranch', 'CO_HIGHLANDS_RANCH', 'active', 'franchise'),
  ('Leetsdale', 'CO_LEETSDALE', 'active', 'franchise'),
  ('Dover', 'DE_DOVER', 'active', 'franchise'),
  ('Newark', 'DE_NEWARK', 'active', 'franchise'),
  ('Wilmington', 'DE_WILMINGTON', 'active', 'franchise'),
  ('Boca Raton', 'FL_BOCA_RATON', 'active', 'franchise'),
  ('Bradenton', 'FL_BRADENTON', 'active', 'franchise'),
  ('Palm Harbor', 'FL_PALM_HARBOR', 'active', 'franchise'),
  ('St. Petersburg', 'FL_ST_PETERSBURG', 'active', 'franchise'),
  ('Tampa', 'FL_TAMPA', 'active', 'franchise'),
  ('Wellington', 'FL_WELLINGTON', 'active', 'franchise'),
  ('Hiram', 'GA_HIRAM', 'active', 'franchise'),
  ('Kennesaw', 'GA_KENNESAW', 'active', 'franchise'),
  ('Seven Hills', 'GA_SEVEN_HILLS', 'active', 'franchise'),
  ('Bloomington', 'IN_BLOOMINTON', 'active', 'franchise'),
  ('Overland Park', 'KS_OVERLAND_PARK', 'active', 'franchise'),
  ('Overland Park South', 'KS_OVERLAND_PARK_SOUTH', 'active', 'franchise'),
  ('Bel Air', 'MD_BEL_AIR', 'active', 'franchise'),
  ('Denton', 'MD_DENTON', 'active', 'franchise'),
  ('Edgewater', 'MD_EDGEWATER', 'active', 'franchise'),
  ('Hunt Valley', 'MD_HUNT_VALLEY', 'active', 'franchise'),
  ('Middle River', 'MD_MIDDLE_RIVER', 'active', 'franchise'),
  ('Severna Park', 'MD_SEVERNA_PARK', 'active', 'franchise'),
  ('Westminster', 'MD_WESTMINSTER', 'active', 'franchise'),
  ('Ballwin', 'MO_BALLWIN', 'active', 'franchise'),
  ('House Springs', 'MO_HOUSE_SPRINGS', 'active', 'franchise'),
  ('Oakville', 'MO_OAKVILLE', 'active', 'franchise'),
  ('St. Charles', 'MO_ST_CHARLES', 'active', 'franchise'),
  ('Washington', 'MO_WASHINGTON', 'active', 'franchise'),
  ('Oxford', 'MS_OXFORD', 'active', 'franchise'),
  ('Long Island', 'NY_LONG_ISLAND', 'active', 'franchise'),
  ('Cincinnati', 'OH_CINCINNATI', 'active', 'franchise'),
  ('Huber Heights', 'OH_HUBER_HEIGHTS', 'active', 'franchise'),
  ('Kettering', 'OH_KETTERING', 'active', 'franchise'),
  ('Mason', 'OH_MASON', 'active', 'franchise'),
  ('Miamisburg', 'OH_MIAMISBURG', 'active', 'franchise'),
  ('Springfield', 'OH_SPRINGFIELD', 'active', 'franchise'),
  ('Ardmore', 'OK_ARDMORE', 'active', 'franchise'),
  ('Broken Arrow', 'OK_BROKEN_ARROW', 'active', 'franchise'),
  ('Chickasha', 'OK_CHICKASHA', 'active', 'franchise'),
  ('Del City', 'OK_DEL_CITY', 'active', 'franchise'),
  ('Durant', 'OK_DURANT', 'active', 'franchise'),
  ('Edmond South', 'OK_EDMOND_SOUTH', 'active', 'franchise'),
  ('Edmond West', 'OK_EDMOND_WEST', 'active', 'franchise'),
  ('Lawton', 'OK_LAWTON', 'active', 'franchise'),
  ('Moore', 'OK_MOORE', 'active', 'franchise'),
  ('Nichols Hills', 'OK_NICHOLS_HILLS', 'active', 'franchise'),
  ('Norman East', 'OK_NORMAN_EAST', 'active', 'franchise'),
  ('Norman West', 'OK_NORMAN_WEST', 'active', 'franchise'),
  ('Northwest OKC', 'OK_NORTHWEST_OKC', 'active', 'franchise'),
  ('Owasso', 'OK_OWASSO', 'active', 'franchise'),
  ('Ponca City', 'OK_PONCA_CITY', 'active', 'franchise'),
  ('Shawnee', 'OK_SHAWNEE', 'active', 'franchise'),
  ('South OKC', 'OK_SOUTH_OKC', 'active', 'franchise'),
  ('South Tulsa', 'OK_SOUTH_TULSA', 'active', 'franchise'),
  ('Stillwater', 'OK_STILLWATER', 'active', 'franchise'),
  ('Tulsa', 'OK_TULSA', 'active', 'franchise'),
  ('Yukon', 'OK_YUKON', 'active', 'franchise'),
  ('Glenolden', 'PA_GLENOLDEN', 'active', 'franchise'),
  ('Port Richmond', 'PA_PORT_RICHMOND', 'active', 'franchise'),
  ('Stroudsburg', 'PA_STROUDSBURG', 'active', 'franchise'),
  ('Thorndale', 'PA_THORNDALE', 'active', 'franchise'),
  ('Chattanooga', 'TN_CHATTANOOGA', 'active', 'franchise'),
  ('Hixson', 'TN_HIXSON', 'active', 'franchise'),
  ('Memphis', 'TN_MEMPHIS', 'active', 'franchise'),
  ('Abilene', 'TX_ABILENE', 'active', 'franchise'),
  ('Addison', 'TX_ADDISON', 'active', 'franchise'),
  ('Alliance', 'TX_ALLIANCE', 'active', 'franchise'),
  ('Arlington', 'TX_ARLINGTON', 'active', 'franchise'),
  ('Bedford', 'TX_BEDFORD', 'active', 'franchise'),
  ('Burleson', 'TX_BURLESON', 'active', 'franchise'),
  ('Coppell', 'TX_COPPELL', 'active', 'franchise'),
  ('Dallas HP', 'TX_DALLAS_HP', 'active', 'franchise'),
  ('Denton', 'TX_DENTON', 'active', 'franchise'),
  ('Garland', 'TX_GARLAND', 'active', 'franchise'),
  ('Highland Village', 'TX_HIGHLAND_VILLAGE', 'active', 'franchise'),
  ('Hulen', 'TX_HULEN', 'active', 'franchise'),
  ('Keller', 'TX_KELLER', 'active', 'franchise'),
  ('Little Elm', 'TX_LITTLE_ELM', 'active', 'franchise'),
  ('McKinney', 'TX_MCKINNEY', 'active', 'franchise'),
  ('Mockingbird Station', 'TX_MOCKINGBIRD_STATION', 'active', 'franchise'),
  ('Plano', 'TX_PLANO', 'active', 'franchise'),
  ('Prosper', 'TX_PROSPER', 'active', 'franchise'),
  ('Roanoke', 'TX_ROANOKE', 'active', 'franchise'),
  ('Rockwall', 'TX_ROCKWALL', 'active', 'franchise'),
  ('Saginaw', 'TX_SAGINAW', 'active', 'franchise'),
  ('Tyler', 'TX_TYLER', 'active', 'franchise'),
  ('Uptown Dallas', 'TX_UPTOWN_DALLAS', 'active', 'franchise'),
  ('Waxahachie', 'TX_WAXAHACHIE', 'active', 'franchise'),
  ('Weatherford', 'TX_WEATHERFORD', 'active', 'franchise'),
  ('West Worth', 'TX_WEST_WORTH', 'active', 'franchise'),
  ('Wylie', 'TX_WYLIE', 'active', 'franchise')
ON CONFLICT (abbreviation) DO NOTHING;
