// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gynvafivzdtdqojuuoit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5bnZhZml2emR0ZHFvanV1b2l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NzgxODgsImV4cCI6MjA2NjQ1NDE4OH0.aYFMOcBZsTg4HNhFQldpPBEKwOvwXGVzmPQPO3UHCxU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);